/* App.svelte generated by Svelte v3.44.0 */
import {
  create_ssr_component,
  missing_component,
  validate_component,
} from 'svelte/internal'

const App = create_ssr_component(($$result: any, $$props: any) => {
  const { component, slots, props } = $$props

  return `${validate_component(component || missing_component, 'svelte:component').$$render($$result, Object.assign(props), {}, {
    default: () => `${slots.default
      ? `<iles-content><!-- HTML_TAG_START -->${slots.default}<!-- HTML_TAG_END --></iles-content>`
      : ''}`,
  })}`
})

export default App
