[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = "playground/the-vue-point/dist"
  ignore = "./scripts/doc-checks.sh"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build && npx pnpm run build:blog"
