packages:
  - docs
  - packages/hydration/
  - packages/prerender/
  - packages/modules/
  - packages/frontmatter/
  - packages/headings/
  - packages/icons/
  - packages/iles/
  - playground/the-vue-point/
