packages:
  - docs
  - packages/hydration/
  - packages/prerender/
  - packages/headings/
  - packages/mdx/
  - packages/icons/
  - packages/pages/
  - packages/prism/
  - packages/iles/
  - playground/the-vue-point/
