// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Author: typeof import('./src/components/Author.vue')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    DefaultLayout: typeof import('./src/layouts/default.vue')['default']
    Island: typeof import('iles')['Island']
    PostDate: typeof import('./src/components/PostDate.vue')['default']
    Quicklink: typeof import('./src/components/Quicklink.ts')['default']
  }
}

export { }
