// generated by iles
// We suggest you to commit this file into source control

declare global {
  const definePageComponent: typeof import('iles')['definePageComponent']
  const useHead: typeof import('iles')['useHead']
  const usePage: typeof import('iles')['usePage']
  const useRoute: typeof import('iles')['useRoute']
}

export { }
