// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Author: typeof import('./src/components/Author.vue')['default']
    BackLink: typeof import('./src/components/BackLink.tsx')['default']
    DefaultLayout: typeof import('./src/layouts/default.vue')['default']
    Head: typeof import('@vueuse/head')['Head']
    Island: typeof import('./../../packages/iles/dist/client/app/components/Island.vue')['default']
    MetaTags: typeof import('./src/components/MetaTags.vue')['default']
    NavBarLinks: typeof import('./src/components/NavBarLinks.svelte')['default']
    PostDate: typeof import('./src/components/PostDate.vue')['default']
  }
}

export { }
