#!/bin/bash

# scripts/test-cypress: Starts the local server and runs Cypress tests.
set -e
cd "$(dirname "$0")/.."

echo '== Starting server =='
pnpm run preview &

echo '== Waiting for server to respond... =='
pnpx wait-on http-get://localhost:3050 --delay 1000 --timeout 15000

echo '== Server ready! =='

pnpx cypress@10.6.0 run && echo '== Finished! =='
