/* App.svelte generated by Svelte v3.43.2 */
import {
  create_ssr_component,
  missing_component,
  validate_component,
} from 'svelte/internal'

const App = create_ssr_component(($$result, $$props, $$bindings, slots$1) => {
  const { component, slots, props } = $$props

  return `${validate_component(component || missing_component, 'svelte:component').$$render($$result, Object.assign(props), {}, {
    default: () => `${slots.default ? `${slots.default}` : ''}`,
  })}`
})

export default App
