// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AlgoliaSearchBox: typeof import('./src/components/AlgoliaSearchBox.vue')['default']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    Author: typeof import('./src/components/Author.vue')['default']
    'Bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Bx:bxSearch': typeof import('~icons/bx/bx-search')['default']
    'Bx:bxSun': typeof import('~icons/bx/bx-sun')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    DarkModeSwitch: typeof import('./src/components/DarkModeSwitch.vue')['default']
    DocSearchBox: typeof import('./src/components/DocSearchBox.vue')['default']
    IconButton: typeof import('./src/components/IconButton.vue')['default']
    'Iles:Logo': typeof import('~icons/iles/-logo')['default']
    InlineSvg: typeof import('./src/components/InlineSvg.vue')['default']
    Island: typeof import('iles')['Island']
    Layout: typeof import('iles')['Layout']
    LinkIcon: typeof import('./src/components/LinkIcon.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    NavBarButton: typeof import('./src/components/NavBarButton.vue')['default']
    NavBarIcon: typeof import('./src/components/NavBarIcon.vue')['default']
    NavBarLink: typeof import('./src/components/NavBarLink.vue')['default']
    NavBarLinks: typeof import('./src/components/NavBarLinks.vue')['default']
    NavBarLogo: typeof import('./src/components/NavBarLogo.vue')['default']
    NavBarMenu: typeof import('./src/components/NavBarMenu.vue')['default']
    OutboundLink: typeof import('./src/components/OutboundLink.vue')['default']
    PostDate: typeof import('./src/components/PostDate.vue')['default']
    Quicklink: typeof import('./src/components/Quicklink.ts')['default']
    TheHeader: typeof import('./src/components/TheHeader.ts')['default']
    TheNavBar: typeof import('./src/components/TheNavBar.vue')['default']
  }
}

export { }
