// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    'Bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Bx:bxSearch': typeof import('~icons/bx/bx-search')['default']
    'Bx:bxSun': typeof import('~icons/bx/bx-sun')['default']
    'Carbon:arrowLeft': typeof import('~icons/carbon/arrow-left')['default']
    'Carbon:pen': typeof import('~icons/carbon/pen')['default']
    CarbonArrowLeft: typeof import('~icons/carbon/arrow-left')['default']
    CarbonArrowRight: typeof import('~icons/carbon/arrow-right')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonLogoTwitter: typeof import('~icons/carbon/logo-twitter')['default']
    DarkModeSwitch: typeof import('./src/components/DarkModeSwitch.vue')['default']
    DocSearchBox: typeof import('./src/components/DocSearchBox.vue')['default']
    EditLink: typeof import('./src/components/EditLink.vue')['default']
    'HeroiconsOutline:menuAlt2': typeof import('~icons/heroicons-outline/menu-alt2')['default']
    HomeHero: typeof import('./src/components/HomeHero.vue')['default']
    Iles: typeof import('./src/components/Iles.vue')['default']
    'Iles:Logo': typeof import('~icons/iles/-logo')['default']
    'Iles:Text': typeof import('~icons/iles/-text')['default']
    'Iles:Vite': typeof import('~icons/iles/-vite')['default']
    IlesLogo: typeof import('~icons/iles/logo')['default']
    Island: typeof import('iles')['Island']
    LastUpdated: typeof import('./src/components/LastUpdated.vue')['default']
    NavBarButton: typeof import('./src/components/NavBarButton.vue')['default']
    NavBarLink: typeof import('./src/components/NavBarLink.vue')['default']
    NavBarLinks: typeof import('./src/components/NavBarLinks.vue')['default']
    NavBarLogo: typeof import('./src/components/NavBarLogo.vue')['default']
    NextAndPrevLinks: typeof import('./src/components/NextAndPrevLinks.vue')['default']
    OutboundLink: typeof import('./src/components/OutboundLink.vue')['default']
    PageFooter: typeof import('./src/components/PageFooter.vue')['default']
    SidebarBackground: typeof import('./src/components/SidebarBackground.vue')['default']
    SidebarHeader: typeof import('./src/components/SidebarHeader.vue')['default']
    SidebarLink: typeof import('./src/components/SidebarLink.vue')['default']
    SidebarLinkItem: typeof import('./src/components/SidebarLinkItem.vue')['default']
    SidebarNav: typeof import('./src/components/SidebarNav.vue')['default']
    SidebarToggle: typeof import('./src/components/SidebarToggle.vue')['default']
    TableOfContents: typeof import('./src/components/TableOfContents.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheNavBar: typeof import('./src/components/TheNavBar.vue')['default']
    TheRightSidebar: typeof import('./src/components/TheRightSidebar.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    TimeAgo: typeof import('./src/components/TimeAgo.vue')['default']
    Tip: typeof import('./src/components/Tip.vue')['default']
    ViteLogo: typeof import('./src/components/ViteLogo.vue')['default']
  }
}

export { }
