// Generated by 'unplugin-auto-import'
export {}
declare global {
  const definePageComponent: typeof import('iles')['definePageComponent']
  const useDocuments: typeof import('iles')['useDocuments']
  const useHead: typeof import('iles')['useHead']
  const usePage: typeof import('iles')['usePage']
  const useRoute: typeof import('iles')['useRoute']
}
