name: cypress

on: [push, pull_request]

jobs:
  cypress:
    if: (! git diff --quiet 'HEAD^' HEAD docs) || ${{ contains(github.event.head_commit.message, 'docs') }}
    name: docs cypress
    env:
      CI: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.10.3
          run_install: |
            - recursive: false

      - name: Docs TS Check
        run: pnpm docs:check

      - name: Build Docs Site
        run: pnpm docs:build

      - name: Cypress
        run: cd docs && pnpm run cy:run
