name: docs

on:
  push:
    branches:
      - main
      - docs

jobs:
  build:
    if: ${{ startsWith(github.event.head_commit.message, 'docs') }}
    name: docs
    env:
      BUILD_HOOK: ${{secrets.NETLIFY_DOCS_BUILD_HOOK}}
    runs-on: ubuntu-latest
    steps:
      - run: 'curl -X POST -d {} $BUILD_HOOK'
